### ISSUE TITLE
Breaks because of drone-go changes

### ISSUE THREAD

**Issue by rrezel** [drone-plugins/drone-webhook#15]
go get -t ./...
package github.com/drone/drone-go/plugin: cannot find package "github.com/drone/drone-go/plugin" in any of:
    /usr/local/go/src/github.com/drone/drone-go/plugin (from $GOROOT)
    /drone/src/github.com/drone/drone-go/plugin (from $GOPATH)

**Comment by tboerger** [comment]
Future version won't use this lib anymore.
