### ISSUE TITLE
Exposing secret to headers

### ISSUE THREAD

**Issue by jacobrosenthal** [drone-plugins/drone-webhook#30]
Im trying to add authorization headers, but theres very little I can find on how this is supposed to be done and no matter what I do Im getting 401 bad auth. This is the most interesting configuration Ive tried as it appears to eat the token in the log, perhaps knowing it shouldn't show it as a secret:

```
  notify:
    secrets: [ github_token ]
    image: plugins/webhook
    pull: true
    urls:
      - https://api.github.com/repos/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}/issues/${DRONE_PULL_REQUEST}/comments
    headers:
      - "Authorization=token ${GITHUB_TOKEN}"
    content_type: application/json
    template: >
      {
        "body": "test",
      }
    when:
      status: [ success ]
    debug: true
```

```
Webhook 1
  URL: https://api.github.com/repos/xxxx/yyyy/issues/26/comments
  METHOD: POST
  HEADERS: map[Content-Type:[application/json] Authorization:[token]]
  REQUEST BODY: {
  "body": "test",
}
  RESPONSE STATUS: 401 Unauthorized
  RESPONSE BODY: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
```

Any pointers appreciated.

**Comment by jacobrosenthal** [comment]
Ive all but confirmed this a correct implementation of both the github api and the auth header string, as Ive been successful running locally. So theres just something incorrect about the way im exposing the secret to the header string via the yaml script.

**Comment by tboerger** [comment]
Thank you for your report, but secrets are not evaluated or replaced within the headers section, please use the username and password secrets (tokens also work as passwords), they are working totally fine.

**Comment by jacobrosenthal** [comment]
Thanks for confirming that solution is a no go. It sounds like you're saying something like this is the proper solution:
```
  notify:
    secrets: [ github_token ]
    image: plugins/webhook
    pull: true
    username: jacobrosenthal
    password: $GITHUB_TOKEN
    urls:
      - https://api.github.com/repos/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}/issues/${DRONE_PULL_REQUEST}/comments
    template: >
      {
        "body": "test"
      }
    when:
      status: [ success ]
    debug: true
```
but thats not accepting the credentials either. Could you clarify further?

**Comment by tboerger** [comment]
Your still used it a little bit wrong, try it like this:

```diff
  notify:
-   secrets: [ github_token ]
+   secrets:
+     - source: github_token
+       target: webhook_password
    image: plugins/webhook
    pull: true
    username: jacobrosenthal
-   password: $GITHUB_TOKEN
    urls:
      - https://api.github.com/repos/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}/issues/${DRONE_PULL_REQUEST}/comments
    template: >
      {
        "body": "test"
      }
    when:
      status: [ success ]
    debug: true
```

**Comment by jacobrosenthal** [comment]
Wow. Confirmed working for me. Thank you. I recall seeing that secrets section in the documentation and couldn't understand its usage at all. May I PR a secrets example to the docs here?

**Comment by jacobrosenthal** [comment]
And if so, would you want that here in docs.md or https://github.com/drone/drone-plugin-index/blob/master/content/drone-plugins/drone-webhook/index.md or both

**Comment by tboerger** [comment]
For https://github.com/drone/drone-plugin-index/blob/master/content/drone-plugins/drone-webhook/index.md I would suggest an example like https://github.com/drone/drone-plugin-index/pull/129/files#diff-30c88d0932cca1f0e8862d7c29834435R63.

If you got an idea how we can further improve https://github.com/drone/docs/blob/master/content/usage/secrets/secrets.md#alternate-names feel free to come up with another PR ;)

**Comment by jacobrosenthal** [comment]
Yeah I guess thats decent documentation (now that I know what it means). I think its just all so disparate I couldnt put it all together. Especially without the facts that a secret wouldnt expand outside of presumably only the 'command' and that a token could be used as a password.

Would it be true to add to secrets.md that secrets are ONLY written out as environment variables for commands and arent usable anywhere else, maybe with an anti example trying to use it in one of the other yaml configurations like header as I did?

I made an attempt at a pr [here](https://github.com/drone/drone-plugin-index/pull/133), happy to discuss any changes there.

Thanks for all the help and the great tools.

**Comment by tboerger** [comment]
Great that it's working for you

**Comment by krantideep95** [comment]
I am facing similar kind of issue.
I am trying to use webhook to push notifications using pushbullet. Sample curl call:
``` console
curl --header 'Access-Token: <your_access_token_here>' \
     --header 'Content-Type: application/json' \
     --data-binary '{"body":"Space Elevator, Mars Hyperloop, Space Model S (Model Space?)","title":"Space Travel Ideas","type":"note"}' \
     --request POST \
     https://api.pushbullet.com/v2/pushes
```
I am not able to insert access_token into header. I have tried different methods like jacobrosenthal's. But still I am failing. This is what I have been trying:
```
webhook:
    image: plugins/webhook
    secrets:
      - source: pushbullet_token
        target: access_token
    urls: https://api.pushbullet.com/v2/pushes
    content_type: application/json
    debug: true
    template: |
       {
       "title": "{{ repo.name }}",
       "body": "{{ build.status }}",
       "type": "note",
       "email": "kranti.deep@gmail.com"
       }
    when:
      event:
        include: [push]
```
for 

```
    secrets:
      - source: pushbullet_token
        target: access_token
```
I have tried `webhook_password` instead of `access_token` in target, but it still didn't work.

Any help is appreciated.

**Comment by tboerger** [comment]
So far secrets can't be injected into the headers, so it's not possible to authenticate with this special header without sharing the token with anybody that got read access to your repo.

**Comment by idcooldi** [comment]
> I am facing similar kind of issue.
> I am trying to use webhook to push notifications using pushbullet. Sample curl call:
> 
> ```
> curl --header 'Access-Token: <your_access_token_here>' \
>      --header 'Content-Type: application/json' \
>      --data-binary '{"body":"Space Elevator, Mars Hyperloop, Space Model S (Model Space?)","title":"Space Travel Ideas","type":"note"}' \
>      --request POST \
>      https://api.pushbullet.com/v2/pushes
> ```
> 
> I am not able to insert access_token into header. I have tried different methods like jacobrosenthal's. But still I am failing. This is what I have been trying:
> 
> ```
> webhook:
>     image: plugins/webhook
>     secrets:
>       - source: pushbullet_token
>         target: access_token
>     urls: https://api.pushbullet.com/v2/pushes
>     content_type: application/json
>     debug: true
>     template: |
>        {
>        "title": "{{ repo.name }}",
>        "body": "{{ build.status }}",
>        "type": "note",
>        "email": "kranti.deep@gmail.com"
>        }
>     when:
>       event:
>         include: [push]
> ```
> 
> for
> 
> ```
>     secrets:
>       - source: pushbullet_token
>         target: access_token
> ```
> 
> I have tried `webhook_password` instead of `access_token` in target, but it still didn't work.
> 
> Any help is appreciated.

Hi, [here](https://github.com/idcooldi/drone-webhook) is authorization support for the `bearer` header.
