### ISSUE TITLE
Status Successful when HTTP response from remote server >= 400

### ISSUE THREAD

**Issue by dokshukin** [drone-plugins/drone-webhook#35]
Expected behaviour: Status Failed

![drone_webhook_screenshot](https://user-images.githubusercontent.com/23241156/50146164-76614b00-02b3-11e9-8ace-63a60132e8af.png)

**Comment by tboerger** [comment]
So far the plugin doesn't care about the response code. I think we could add a int slice attribute which is empty by default and keeps the current behavior, but which can get a slice of acceptable status codes and fails if none of them are given.

**Comment by dokshukin** [comment]
@tboerger thank you for the fast response.
There is a [check](https://github.com/drone-plugins/drone-webhook/blob/master/plugin.go#L144) for the response status code.
May be, it will be easier to add the flag, f.e. `FAIL_ON_HTTP_ERRORS = false` (to keep current behaviour) add it into [config](https://github.com/drone-plugins/drone-webhook/blob/master/plugin.go#L38) structure, and return error [here](https://github.com/drone-plugins/drone-webhook/blob/master/plugin.go#L162)?

**Comment by tboerger** [comment]
There is just a check to get some debug information. I would prefer a patch that accepts a list of acceptable http codes as mentioned above to fail a build if the http code is not within the list.

**Comment by tboerger** [comment]
A pull request would be much appreciated :)

**Comment by chrl** [comment]
https://github.com/drone-plugins/drone-webhook/pull/36

**Comment by dokshukin** [comment]
Thank you
