### ISSUE TITLE
Problem not recognising URL

### ISSUE THREAD

**Issue by ficofer** [drone-plugins/drone-webhook#49]
Problem not recognising URL

I am using it like this @tboerger and its failing :

```
2019/09/04 15:44:16 You must provide at least one url
```

```
   webhook: 
     image: plugins/webhook
     settings:
       urls: https://web_hook.myhook.com
       content_type: application/json
       template: >
           "#### My Msg ..."
     debug: true
     when:
       branch: develop
```

**Comment by techknowlogick** [comment]
I think you are combining 0.8syntax and 1.x syntax. I'm on mobile right now so I can't provide an example but I'll try to find one later.

**Comment by tboerger** [comment]
Yep, looks like you try the 1.0.0 schema on a 0.8 drone

**Comment by ficofer** [comment]
@tboerger how is the 0.8 schema? I was not able to find it anywhere.

**Comment by techknowlogick** [comment]
try:
```
---
kind: pipeline
type: docker
name: default

steps:
- name: send
  image: plugins/webhook
  settings:
       urls: https://web_hook.myhook.com
       content_type: application/json
       template: >
           "#### My Msg ..."
       debug: true
  when:
    branch:
    - develop
```
(this is a complete drone yaml to send a webhook in 1.x syntax)

**Comment by ficofer** [comment]
Thanks! @techknowlogick I think that worked but the issue change somehow, I decided to update and go to 1.0 version.

When I connect it I end up having a webhook in Bitbucket like  https://drone.myweb.com/hook?access_token=###LONG_KEY###

When I curl that ur ^^ from my terminal I get a 200.

But when Bitbucket post the request to start a pipeline it gets a 404 after 10k mili seconds.

```
Type: repo:push
Event time: a minute ago (Wednesday, September 4th 2019, 8:11:21 pm)
Response from https://drone.myweb.com/hook?access_token=###LONG_KEY###
HTTP status: 404
Elapsed time: 10592ms
Request time: a minute ago (Wednesday, September 4th 2019, 8:11:31 pm)
```

Any idea in how I can troubleshoot that?

**Comment by techknowlogick** [comment]
Drone webhooks have changed between 0.8 and 1.x, and will need to be updated in bitbucket. Simplest way is deactivating repo and then activating it again. I suggest reading the migration tool documentation: https://github.com/drone/drone-migrate to ensure you have migrated correctly. If you have any issues with that I recommend the forum https://discourse.drone.io/ or chat https://gitter.im/drone/drone as places for assistance. Here is also a helpful guide for receiving support from Drone team: https://discourse.drone.io/t/how-to-ask-for-help/3483

I will close this now as the original Q has been answered.
