### ISSUE TITLE
build.deployTo is missing from the usable properties

### ISSUE THREAD

**Issue by Jakob-em** [drone-plugins/drone-webhook#52]
I tried to use the webhook plugin for a custom webhook i am working on and found out that i have no access to the DRONE_DEPLOY_TO property from inside the template. I saw that the slack plugin supports this property (build.deployTo) and it would be nice to see it here too. Is there any specific reason for this missing property?

**Comment by tboerger** [comment]
No specific reason that it's missing it

**Comment by Jakob-em** [comment]
Ok thanks for the info. I will try to make a pull request to add it later this day.

**Comment by tboerger** [comment]
Solved by #53
