### ISSUE TITLE
DRONE_BUILD_STATUS always "success" for kubernetes runner

### ISSUE THREAD

**Issue by krohrsb** [drone-plugins/drone-webhook#55]
The `DRONE_BUILD_STATUS` environment variable is always `success` when running via kubernetes. See the following discourse discussion for more details:

https://discourse.drone.io/t/drone-build-status-always-success-in-kubernetes/6627/2

The slack plugin has already implemented a solution in its plugin. So looking for something similar for the webhook plugin.

https://github.com/drone-plugins/drone-slack/blob/master/main.go#L187-L189

**Comment by tboerger** [comment]
The available environment variables are not set by plugins. Please write on discourse.drone.io, I even guess there is already some thread related to that.

**Comment by tboerger** [comment]
The env file will be parsed by all plugins implementing the bvoilr templated defined at https://github.com/drone-plugins/boilr-plugin/pull/8/commits/0b5230b139774d4842e4c5b37ab06521383b1172
