### ISSUE TITLE
Unusable secrets in headers.

### ISSUE THREAD

**Issue by hickscorp** [drone-plugins/drone-webhook#57]
We've seen similar issues but the suggested solutions didn't work for us. Here is how we use the webhook plug-in in one of our pipelines:

```
  - name: mattermost-notify
    image: plugins/webhook
    settings:
      urls:
        - https://whatever.com/hooks/abcdef
      headers:
        - Authorization=Bearer fedcba
      valid-response: 200
      template: >
        {
          "text": "[{{repo.name}}:{{build.branch}}] <{{build.link}}|Build {{truncate build.commit 8}}> by {{build.author}} was a {{build.status}}.",
          "channel": "staging-platform-notifications"
        }
    when:
      status: [success, failure]
```

When hard-coded, the webhook works. So now we are trying to substitute `abcdef` and `fedcba` by secrets. We tried all combinations of:

- Using `${MATTERMOST_WEBHOOK_ID}`. In this case, our secret is just empty.
- Using `$${MATTERMOST_WEBHOOK_ID}`. In this case, the secret looks like `$%37MATTERMOST_WEBHOOK_ID%37`.
- Using an `environment:` block and trying to get the secret and map it to another variable - no joy either.

Could it be that we've uncovered a bug?

**Comment by tboerger** [comment]
It's not a bug, secrets and env variables are simply not evaluated within the webhook payload.

**Comment by hickscorp** [comment]
Good morning @tboerger and thank you for answering the inquiry,
Is there a way to achieve what we're trying to do apart from using secrets? Eg have data from a hidden source used as part of the headers / payload?

**Comment by hickscorp** [comment]
Scratch that last - it worked when trying exactly what I suggested. Thank you @tboerger for your help.
May I suggest that this information (and also "why" it's not possible) would be added to the README? I think if we could understand "why" it is not possible to extrapolate secrets *inside* variables might help someone with proper knowledge to implement the feature in the future?

**Comment by tboerger** [comment]
The why is quite simple, nobody implemented it because of security concerns that some secret could leak on public repositories by some malicious pull request.

But you are right, it would make sense to document it on the plugin index that secrets and env variables aren't evaluated.

The pre-defined drone variables are only working because drone is evaluating that while rendering the build config.

**Comment by tboerger** [comment]
Why aren't you using the slack plugin for mattermost notifications? AFAIK they got the same API.
